remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Rahul Mahadik
description: Power BI | SQL | Python | Excel
linkedin: https://www.linkedin.com/in/rahulpunarathraomahadik/
logo: Self photo - Copy.jpg
